Unmark as public facing package.
customink/stuffed_bunny pull request #13
Opened 2024-06-21 14:05 UTC by mscavnicky

### Stakeholder Overview _[(learn more)](https://app.getguru.com/card/TGyLkrnc/Pull-Review-Stakeholder-Overview)_

### Risk Estimate _[(learn more)](https://app.getguru.com/card/iMnRRRjT/Pull-Request-Risk-Estimate)_
_[Replace this with a description of the risk, if any, and how the change will be deployed.]_

- ⚠️ Big/complex change
- ⚠️ Big splash zone
- ⚠️ High stakes if errors occur
- ⚠️ Low confidence
- ⚠️ Not hidden by feature flag
- ✅ Negligible risk!

### Changes

##### Updated Dependencies
 - None

### Ticket

[Monday issue](https://customink.monday.com/boards/12345/pulses/12345)

### Screenshots

### Notes

_Recommended reading: [Code Review guide](https://github.com/customink/guides/blob/master/operations/code-review/README.md)_

### Optional Tasks

- [ ] Include 🎩 Instructions
- [ ] Update the readme (README.md)
- [ ] Update the API or architecture docs (e.g. docs/api.md)

##### Library-Specific

- [ ] Increment the changelog (CHANGELOG.md)
- [ ] Increment the version number (lib/version.rb)
- [ ] [Release & Tag][release] the version above in Github

[release]: https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

##### Performance
- Are there any new queries in your change set that might require new indexes?
- Do any new queries require time-boxing to avoid table-scans when the data grows?

##### Data & Analytics Dependencies
- For customer-facing applications, are there any GA tagging changes that are needed or created by this change? If so, have those been discussed with D&A?
- Has Data Engineering been notified of any schema changes?

### What GIF Best Describes This Pull Request?

2024-06-21 18:55 UTC, chmurph2 requested changes
![CleanShot 2024-06-21 at 14 54 55@2x](https://github.com/customink/stuffed_bunny/assets/2841/8233d5ef-3a01-4c3b-afe8-f14650c7ed69)

But it is...

2024-06-26 13:06 UTC, mscavnicky commented
Ha! I think there's been a mishap on what public facing means :)

Public facing in OpsLevel means a public ingress exists that is exposed to the world wide web, which make the application vulnerable to external attacks.

Packages, even though public, would not count in that definition. SPAs are a special case that is currently counted if it is customer facing.

@paulslaby We should probably document this.

2024-06-26 13:45 UTC, paulslaby commented
> @paulslaby We should probably document this.

Added here: https://app.getguru.com/card/T554j7Bc/Catalogyaml/card-history?activeTab=revision-history

2024-06-26 15:41 UTC, chmurph2 approved these changes

2024-06-26 15:41 UTC, merged